### ISSUE TITLE
Transaction import looks for “N/C:” in column 2. This isn’t present in the most recent PWYF Sage export

### ISSUE THREAD

**Issue by andylolz** [markbrough/sage-iati#8]
I’m not sure if there’s an extra step required in the Sage export, or if Sage has changed in some way… But for the most recent PWYF Sage export, sage-to-iati fails to find any transactions. That’s because the parser searches for `N/C:` in column 2, but these values are not present in the most recent export.

If I add these `N/C:`s in, everything seems to work fine. I can send a PR to get this tool to work with the spreadsheet data I’m seeing, but I wonder if it’s possible that the spreadsheet data was exported incorrectly?

**Comment by markbrough** [comment]
I am pretty sure this is a problem with the latest export. The latest data I parsed (exported on 20/10/2015) looked slightly different from the previous version, as Sage was updated. Assuming Sage has not been updated again since October (unlikely), the export should be the same.

I think the N/Cs are important to determine the (economic) "sector" of the spending, e.g. "Salaries & Wages", "IT Technical Assistance", etc.

The user interface has instructions on how the data has to be exported to get it into the correct format, when you go to upload the data.

**Comment by andylolz** [comment]
> The user interface has instructions on how the data has to be exported to get it into the correct format, when you go to upload the data.

Ah, yes… I read those instructions, but unfortunately I just have access to the exported file (rather than Sage.) I’ll try to sit down with Linda next week and step through those instructions with her.

> I think the N/Cs are important to determine the (economic) "sector" of the spending, e.g. "Salaries & Wages", "IT Technical Assistance", etc.

Yes exactly – The nominal codes themselves are definitely important. Thankfully though, those are present in this export. The only bit that isn’t present is the string `N/C:` in column 2. So it would be possible to work around this and spot these header rows by e.g. examining empty cells in the row. But I won’t attempt to do that before determining whether this relates to the method used to run the export, or an update to Sage.

**Comment by andylolz** [comment]
> Works with:
> - Sage 50 Accounts Plus 2011 (version 17.0.15.208)

Aha – I think the version used here is Sage 50 Accounts 2015 (version 21.0.3.296). So it seems plausible that the export looks quite different.
